### ISSUE TITLE
Complex to real: Imaginary part of first element changes the result

### ISSUE THREAD

**Issue by preiter93** [HEnquist/realfft#11]
Hi,

first, thank you for the super library!

I noticed that the result of the inverse c2r transform depends on the imaginary part of the first element, which is supposed to be purely real. The same for the last element, for an even input. This is different to numpys rfft, which neglects these components. Is this behavior intended, and left to the user to provide correct input?

Here is an example:

fn main() {
    use realfft::RealFftPlanner;

    let length = 6;

    // make a planner
    let mut real_planner = RealFftPlanner::<f64>::new();

    // create an iFFT and input and output vectors
    let c2r = real_planner.plan_fft_inverse(length);
    let mut indata_a = c2r.make_input_vec();
    let mut indata_b = c2r.make_input_vec();
    let mut outdata_a = c2r.make_output_vec();
    let mut outdata_b = c2r.make_output_vec();

    // The first element should be real by definition,
    // so the imaginary part should not matter for the solution, 
    // thus outdata_a and outdata_b should be the same, but they are not.
    indata_a[0].re = 1.;
    indata_a[0].im = 0.;
    indata_b[0].re = 1.;
    indata_b[0].im = 100.;
    c2r.process(&mut indata_a, &mut outdata_a).unwrap();
    c2r.process(&mut indata_b, &mut outdata_b).unwrap();

    println!("{:?}", outdata_a);
    println!("{:?}", outdata_b);

    // ***********************************************
    // PYTHON NUMPY
    // import numpy as np
    // n = 6
    // vhat = np.zeros(n // 2 + 1, dtype=np.complex_)
    // vhat[0] = 1 + 0.0j
    // v_a = np.fft.irfft(vhat, axis=0)
    // vhat[0] = 1 + 100.0j
    // v_b = np.fft.irfft(vhat, axis=0)
    // # Output is equal
    // print(v_a)
    // print(v_b)
    // ***********************************************

    // Assert fails
    // for (a, b) in outdata_a.iter().zip(outdata_b.iter()) {
    //     if (*a - *b).abs() > 1e-6 {
    //         panic!("Large difference of values, got {} and {}.", b, a)
    //     }
    // }

    // Same for the last element if the input length is even,
    // last element should pe purely real.
    indata_a[length / 2].re = 1.;
    indata_a[length / 2].im = 0.;
    indata_b[length / 2].re = 1.;
    indata_b[length / 2].im = 100.;
    c2r.process(&mut indata_a, &mut outdata_a).unwrap();
    c2r.process(&mut indata_b, &mut outdata_b).unwrap();

    println!("{:?}", outdata_a);
    println!("{:?}", outdata_b);

    // Assert fails
    // for (a, b) in outdata_a.iter().zip(outdata_b.iter()) {
    //     if (*a - *b).abs() > 1e-6 {
    //         panic!("Large difference of values, got {} and {}.", b, a)
    //     }
    // }
}

**Comment by HEnquist** [comment]
Thanks for the detailed report! I simply have not considered that the zero elements might have some other values. 
Just ignoring them doesn't feel quite right. If they are non-zero there is probably a bug somewhere, and ignoring them hides that. I think checking the values and returning an error is safer.

**Comment by preiter93** [comment]
Yes I agree, that would be the safest way

**Comment by HEnquist** [comment]
This is included here: https://github.com/HEnquist/realfft/pull/12
