### ISSUE TITLE
Project works with 2.0.1, but fails with 3.0.0

### ISSUE THREAD

**Issue by spluta** [HEnquist/realfft#14]
Hi @HEnquist. I am using realfft in a project you may enjoy:

https://github.com/spluta/TimeStretch

It is an extreme Paulstretch, if you are familiar with that.

The code works perfectly on 2.0.1, but fails with 3.0.0

It fails on this line:

https://github.com/spluta/TimeStretch/blob/584021b84645c1998becb38e7bd37c27b5893d32/rust/src/main.rs#L579

with error:

`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InputValues(false, true)', src/main.rs:581:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/main.rs:488:12
`

The algorithm needs to randomize the phase. If I do this, I get this error. If I just convert the values to Polar and back to Complex without changing anything, I get the error. If I set all the phases to 0.0, there are no errors, but if I set them to any other value, it fails at some point. 

The only consistency I can find is that it is failing when three conditions are met:
1) the original magnitude of the bin is not 0 
2) the original phase of the bin is 0 or PI.
3) I change the mag or phase under those previous two conditions

If i look for conditions 1 and 2 and don't change the mag or phase under those circumstances, the code runs.

Unfortunately I cannot work around this as the mag is always multiplied by a window.

I thought this was because of the multithreading, but it fails even when I remove that.

Any clue as to what may have changed to cause this?

Thanks,

Sam

**Comment by HEnquist** [comment]
Hi! It looks like you are randomizing the phase of all elements, which doesn't work with a complex-to-real iFFT. The first element must always be real, and if the length is even, then also the last element must be real. In version 3.x it checks to make sure of that and returns an error if not. The older version doesn't, and actually returns an incorrect result instead. If you really need to randomize the phase also of the first and last element, then your result becomes complex. And then you need to use a complex-to-complex FFT+IFFT.

**Comment by spluta** [comment]
Hi Henrick,

Oh wow. I didn't realize this was only happening on the top bin. If I don't touch that bin, there is no issue. Thank you.

Actually, with the number of rffts I'm doing, ignoring the top and bottom bins should speed things up a tiny bit.

Thanks!

Sam
