### ISSUE TITLE
Add a method to get the complex-domain length

### ISSUE THREAD

**Issue by cassiersg** [HEnquist/realfft#31]
Sometimes, one cares about the output length of the R2C transform only for allocating an output buffer, and the provided `make_output_vec` cannot be used (e.g. we want to allocate multiple buffers at once).

This requires the computation of the FFT output length, which can be computed as `r2c.len() / 2 + 1`, however this is not very explicit, and it would be more simple to use a method on the FFT object, e..g. `r2c.output_len()` or `r2c.complex_len()`. I think that such a method would be a natural complement to the existing `len` and `get_scratch_len` APIs.

**Comment by HEnquist** [comment]
Great suggestion, thanks! I'll add it in the next minor version. I'll just wait a little to see if something else pops up. If not, I'll make a new version with just this.

**Comment by HEnquist** [comment]
implemented in https://github.com/HEnquist/realfft/pull/38

**Comment by HEnquist** [comment]
Released :)
