### ISSUE TITLE
Increased clarity about word length.

### ISSUE THREAD

**Issue by Easyoakland** [HEnquist/realfft#35]
In the docs/readme it references `length` several times. For example:
"To get normalized results, each element must be scaled by 1/sqrt(length). If the processing involves both an FFT and an iFFT step, it is advisable to merge the two normalization steps to a single, by scaling by 1/length."

What is unclear is that `length` is always referring to the time domain's vector length. I had to experimentally determine this to be the case.

For example taking the `fft(ifft(x))` must be scaled by the length of the `ifft(x)` and not by the length of `fft(ifft(x))` or `x`.

It may be worth including this clarification when `length` is referenced in the docs/readme.

**Comment by HEnquist** [comment]
That's a nice improvement, I'll rewrite this to make it clear which length it refers to.

**Comment by HEnquist** [comment]
implemented in https://github.com/HEnquist/realfft/pull/38

**Comment by Easyoakland** [comment]
Those changes look good! Thanks!
