### ISSUE TITLE
ComplexToReal produces half the expected output amplitude

### ISSUE THREAD

**Issue by nyanpasu64** [HEnquist/realfft#4]
When I take a realfft `RealToComplex` of a (for example) length-16 real vector filled with 1, I get a complex vector with amplitude 16+0j in bin 0 (real). When I take a `ComplexToReal` of the resulting vector, I get a vector filled with 8. This value is equal to length-16 data / 2, or length-9 spectrum - 1.

I expected the inverse real FFT to output all 16s, which is how the underlying rustfft crate behaves when you round-trip a length-16 vector set to 1+0j. To compensate, I must multiply all complex values by 2.0 before performing a `ComplexToReal`. Not sure if other people will agree that my proposed normalization is ideal though.

This behavior doesn't exactly match other FFT libraries I'm aware of. NumPy's rfft is not normalized, whereas irfft is, which is useful for convolution. In my case, I'm normalizing my FFT (RealToComplex), but not IFFT (ComplexToReal), which is useful for spectral analysis so bin amplitudes only depend on input amplitude, and do not change when the input is resampled (changes length, and stretches/interpolates samples).

I believe this can be changed by removing 0.5 from https://github.com/HEnquist/realfft/blob/ee56c1f93516b098b33d233eeedb119ad9c41be4/src/lib.rs#L268-L272 . However this will be a breaking change requiring a version bump. And looking at these formulas, I'm not sure why both r2c and c2r have a 0.5 factor, but only one needs to be removed.

**Comment by HEnquist** [comment]
Thanks! Yes you are right, the current scaling doesn't quite make sense when comparing with other libraries. A non-normalized fft+ifft as in your example should give all 16s. I'll fix that and make a new release. 

I use this for convolution with a fixed impulse response, and to avoid the need for normalizing after every convolution, I "pre-normalize" the transformed impulse response instead.

**Comment by HEnquist** [comment]
Just a small update. I'm working on some improvements to the RustFFT library that will probably lead to a new major version there. I'll wait for that to land before I make this change here. Hopefully that will be quite soon.

**Comment by HEnquist** [comment]
The new version of RustFFT is out, and became a much larger improvement than I hoped for. I'll start on updating this library right away and include the fix for this (togehter with better documentation).

**Comment by HEnquist** [comment]
Version 0.4 is published. It uses RustFFT 5.0 and also fixes this issue.
