### ISSUE TITLE
Is it true that there are no normalizations both in rfft and irfft?

### ISSUE THREAD

**Issue by grazder** [HEnquist/realfft#40]
I was comparing rust implementation with numpy python rfft/irfft and found that your rfft has no normalization and irfft has `1/n` normalization. 

Does irfft have normalization in your implementation?

**Comment by HEnquist** [comment]
RealFFT follows what RustFFT does here, so there is no normalisation in either forward or inverse transforms.
It's mentioned here for RealFFT: https://github.com/HEnquist/realfft#scaling
And here for RustFFT: https://docs.rs/rustfft/latest/rustfft/#normalization
