### ISSUE TITLE
Imaginary parts are non-zero

### ISSUE THREAD

**Issue by TYPEmber** [HEnquist/realfft#41]
I'm working on a N-Dimension convolution crate right now, and I've encountered the same question with the newest version.
This is the repository : https://github.com/TYPEmber/ndarray-conv
And I need to do these things to make it run without errors.
#36 #
```rust
if input.len().is_odd() {
    unsafe { input.uget_mut(0).im = T::zero() };
    unsafe { input.uget_mut(input.len() - 1).im = T::zero() }
} else {
    unsafe { input.uget_mut(0).im = T::zero() };
};
```

**Comment by HEnquist** [comment]
How large are those unwanted imaginary parts, and when and why do they get their non-zero values?

**Comment by TYPEmber** [comment]
I made a mistake in this issue's description, These error only occurs when realfft's backward input len is odd.
These values are comes from realfft's forward result.
Further more, set the head and tail complex number's imaginary part to zero give a correct value for convolution situation.


> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 3.4103622
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.015018316
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -25.074608
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.016035048
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -42.025406
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.035903253
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -45.428547
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.007293839
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -10.569998
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0033008656
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 44.877174
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.0057902485
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 6.2615337
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.0107482
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 3.5118008
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.022698648
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 13.238977
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.058788996
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 16.36588
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.06603317
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 24.77857
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.00340113
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 23.351837
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.009029526
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -25.304758
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.02839218
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 3.3011112
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.03883362
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 69.3352
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.002621321
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -33.688812
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.07077228
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -28.24574
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.02656883
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 46.763992
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0035043433
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 0.58330154
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0062466636
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -4.6635027
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.043604
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -13.987614
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.023332436
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -2.9922771
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.017952919
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 1.0276175
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.03191544
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 9.216724
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.014404015
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -1.6693211
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.02220102
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 29.918499
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.024564285
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 77.50005
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.027704043
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -17.97854
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.017279934
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 35.13748
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.007434519
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 34.110687
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.044131838
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -31.413977
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.00036229193
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 24.706455
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.049514815
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 32.353664
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.029096399
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -36.849083
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.009471579
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -59.788628
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.0031445622
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -35.92873
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.030222299
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -59.352894
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0077836877
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -14.180353
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.006800756
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 53.527466
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0046639405
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -41.924496
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.01886597
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -54.156418
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.02689378
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -28.678135
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.07004659
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -61.244488
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0045020543
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -31.408447
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.02779793
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -11.419661
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.052693106
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -61.44487
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.014386116
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -17.036491
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.055303946
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -12.781118
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.02588509
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -30.953304
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.003482163
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 11.081137
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.0221998
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 17.831833
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0056352187
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -47.586494
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.024328921
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -22.6548
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.023018032
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -2.7484493
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.014528286
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -54.973175
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.012238806
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 28.74476
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.030392727
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 9.2536125
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.045300413
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -29.013817
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.00067616254
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -26.243872
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.039956015
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -52.688137
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.012620429
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -77.30587
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.04806872
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -20.034517
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.03557181
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = 6.624254
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.05126635
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -58.1251
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.044863973
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -11.649233
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.009375269
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -39.766014
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.035645675
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -46.04451
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.023395453
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -61.735794
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.017483704
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -57.063286
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.011693316
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -64.86644
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.038120914
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -16.750343
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.0172331
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -43.960506
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.0021296586
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -50.077274
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.010073591
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -65.21934
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.0023525394
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -40.37059
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.0044712853
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -69.16498
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.01594908
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -46.857986
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.036603317
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -14.854864
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.016908437
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -73.42756
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = -0.006634891
> [src/conv_fft/fft.rs:108:21] input.uget_mut(0).im = -30.69054
> [src/conv_fft/fft.rs:109:21] input.uget_mut(input.len() - 1).im = 0.03920153

**Comment by HEnquist** [comment]
Those are quite large numbers, not just a bit of numerical noise. That makes it look like an error somewhere in the math. A spectrum for a real signal must have zeroes in these positions, otherwise it can't be a spectrum of a real signal.
Have you checked that the output is correct after setting these imaginaries to zero?

**Comment by TYPEmber** [comment]
Thanks, I will check my code.

**Comment by TYPEmber** [comment]
I've checked my result with non-fft accelaration ver conv, the difference is less than 1e-3.

```rust
let x = Array::random((1007, 4007), Uniform::new(0f32, 1.));
let k = Array::random((27, 21), Uniform::new(0f32, 1.));

let a = x.conv(k.with_dilation(2), ConvMode::Same, PaddingMode::Zeros).unwrap();
let b = x.conv_fft(
    k.with_dilation(2),
    ConvMode::Same,
    PaddingMode::Zeros,
).unwrap();

let d = a - b;
assert!(d.iter().all(|&v| v.abs() < 1e-3));
```

**Comment by TYPEmber** [comment]
By the way, my crate is a N-Dimension conv lib. So, I use realfft to transform real num to complex num. Then, use the crate rustfft to process these complex num for N > 1 situation.
Is these process introduce additional error？

forward
```rust
for (mut input, mut output) in input.rows_mut().into_iter().zip(output.rows_mut()) {
    rp.process(
        input.as_slice_mut().unwrap(),
        output.as_slice_mut().unwrap(),
    )
    .unwrap();
}

let mut axes: [usize; N] = std::array::from_fn(|i| i);
axes.rotate_right(1);
for _ in 0..N - 1 {
    output_shape.rotate_right(1);

    // transpose takes a lot of time
    // this method is very slow
    // input = Array::from_shape_vec(
    //     raw_dim.into_dimension(),
    //     input.permuted_axes(axes).iter().copied().collect(),
    // )
    // .unwrap();

    let mut buffer = Array::uninit(output_shape.into_dimension());
    buffer.zip_mut_with(&output.permuted_axes(axes), |transpose, &origin| {
        transpose.write(origin);
    });
    output = unsafe { buffer.assume_init() };

    let cp = self.cp.plan_fft_forward(output_shape[N - 1]);
    cp.process(output.as_slice_mut().unwrap());
}
```
backward
```rust
let mut axes: [usize; N] = std::array::from_fn(|i| i);
        axes.rotate_left(1);
        for _ in 0..N - 1 {
            let cp = self.cp.plan_fft_inverse(raw_dim[N - 1]);
            cp.process(input.as_slice_mut().unwrap());

            raw_dim.rotate_left(1);

            let mut buffer = Array::uninit(raw_dim.into_dimension());
            buffer.zip_mut_with(&input.permuted_axes(axes), |transpose, &origin| {
                transpose.write(origin);
            });
            input = unsafe { buffer.assume_init() };
        }

        let mut output_shape = input.raw_dim();
        output_shape[N - 1] = self.rp_origin_len;
        let mut output = Array::zeros(output_shape);

        for (mut input, mut output) in input.rows_mut().into_iter().zip(output.rows_mut()) {
            if input.len().is_odd() {
                unsafe { input.uget_mut(0).im = T::zero() };
                unsafe { input.uget_mut(input.len() - 1).im = T::zero() }
            }
            // else {
            //     unsafe { input.uget_mut(0).im = T::zero() };
            // };

            rp.process(
                input.as_slice_mut().unwrap(),
                output.as_slice_mut().unwrap(),
            )
            .unwrap();
        }
```

**Comment by HEnquist** [comment]
It's not obvious why this doesn't work. The complex FFTs + iFFTs for the N>1 seem to produce something that isn't a valid spectrum for a real signal. 
Have you tried doing a complete FFT + iFFT roundtrip (without doing any convolution) while inspecting the data at each step? The iFFT steps should then just run the process backwards until you are back at the initial data.

**Comment by TYPEmber** [comment]
Thanks for your advice.
I realized that rustfft's output is not been normalized. And after normalized, the FFT + iFFT roundtrip is just the initial data.
So the imaginary parts (after normalized) is

> [src/conv_fft/fft.rs:110:13] input[0].im = -6.71065e-7
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 4.650739e-9
> [src/conv_fft/fft.rs:110:13] input[0].im = -4.1062555e-7
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 1.2193493e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = 9.324834e-7
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 2.7600278e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = -1.9560841e-6
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 7.3624338e-9
> [src/conv_fft/fft.rs:110:13] input[0].im = 4.3599863e-7
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 5.5566527e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = 1.5098113e-6
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 6.7953937e-10
> [src/conv_fft/fft.rs:110:13] input[0].im = 9.405752e-8
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 3.0399264e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = -6.091729e-7
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = -1.2576954e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = 2.4336578e-6
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 3.9196365e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = 3.7106372e-7
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 1.491247e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = 1.423513e-6
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 4.10963e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = -2.8350769e-8
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 1.3021893e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = -5.098982e-6
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = 2.7112398e-8
> [src/conv_fft/fft.rs:110:13] input[0].im = 3.217758e-6
> [src/conv_fft/fft.rs:111:13] input[input.len() - 1].im = -1.4694084e-8

**Comment by HEnquist** [comment]
Great, now the imaginary parts look like they are just numerical noise. 
I don't want to remove the zero-check, it's useful for catching math errors. But I was thinking about adding another trait method that does the iFFT without checking. Or maybe do a debug_assert instead of skip completely

**Comment by TYPEmber** [comment]
Thank you for your patient replay, I will ignore this error for now.
