### ISSUE TITLE
Upgrade to RustFFT 5.0.0

### ISSUE THREAD

**Issue by guimcaballero** [HEnquist/realfft#5]
RustFFT version 5.0.0 has been recently released. [Here](https://github.com/ejmahler/RustFFT/blob/master/UpgradeGuide4to5.md)'s the upgrade guide. It looks like there are some code changes required with this new version.

**Comment by HEnquist** [comment]
Yes I know :) https://github.com/ejmahler/RustFFT/graphs/contributors
I'll update asap!

**Comment by guimcaballero** [comment]
Oh, sorry, I didn't know you worked on the new release! 😅 I'm just very excited for the performance improvements.
