### ISSUE TITLE
Adapt rustfft concurrency example

### ISSUE THREAD

**Issue by Pfeil** [HEnquist/realfft#8]
Hi, I am currently using realfft with a cpal input stream (or trying, at least :D). I wonder if I am doing unnecessary complicated and unsafe stuff. An adaption of rustffts concurrency example (https://github.com/ejmahler/RustFFT/blob/master/examples/concurrency.rs) would help me a lot. To me it did not look as trivial to adapt it as I first thought, even though the API is so similar. Maybe I just don't see it, but well. I think it would help :)

**Comment by HEnquist** [comment]
I hadn't tried sharing an FFT, and realized now that it didn't work since the FFT traits were missing Send and Sync. I added those and released v1.1.0.
See the example here: https://github.com/HEnquist/realfft/blob/master/examples/concurrency.rs

**Comment by HEnquist** [comment]
Did you get it to work?

**Comment by Pfeil** [comment]
Thanks for your fast response, that was faster than I got time to try it out again :D It works perfectly now, without any tricks or unsafe. Thanks :)
